import Link from "next/link";
import { AlertTriangle, ArrowRight, Banknote, BellRing, CalendarCheck, Check, Landmark, ReceiptText, ShieldCheck, Smartphone } from "lucide-react";

export default function Home() {
  return <main className="landing">
    <nav className="landing-nav"><div className="brand-row"><div className="brand-mark small">S</div><div><strong>SafeSpend</strong><span>Register</span></div></div><div><Link className="nav-link" href="/login">Sign in</Link><Link className="button primary small-button" href="/demo">Try the demo</Link></div></nav>
    <section className="landing-hero"><div className="hero-copy"><span className="launch-pill"><BellRing size={15} /> Your checkbook now watches the bank</span><h1>Know what you can safely spend <em>before</em> the balance fools you.</h1><p>SafeSpend reserves recurring bills from the right paycheck, compares your documented register with Plaid bank activity, and texts you when unexplained spending creates a variance.</p><div className="hero-actions"><Link className="button primary large" href="/demo">Open the working demo <ArrowRight size={18} /></Link><Link className="button secondary large" href="/login">Connect a test account</Link></div><div className="trust-row"><span><Check size={16} /> Home-screen PWA</span><span><Check size={16} /> Plaid Sandbox ready</span><span><Check size={16} /> SMS alerts</span></div></div><div className="phone-preview"><div className="preview-top"><span>9:41</span><span>SafeSpend</span><span>•••</span></div><div className="preview-safe"><span>SAFE TO SPEND</span><strong>$863.00</strong><small>After $2,915 reserved for bills</small></div><div className="preview-card"><span>Actual bank balance</span><strong>$3,846.00</strong></div><div className="preview-alert"><AlertTriangle size={20} /><div><strong>$36.86 unexplained</strong><small>2 transactions need review</small></div></div><div className="preview-text"><Smartphone size={21} /><p><strong>SafeSpend alert:</strong> Your balance is $36.86 lower than your register. Tap to review.</p></div></div></section>
    <section className="feature-section"><p className="eyebrow centered">The modern twist</p><h2>It behaves like a register, not another budget spreadsheet.</h2><div className="feature-grid"><article><div className="feature-icon"><CalendarCheck /></div><h3>Payday reservations</h3><p>Mortgage, insurance, utilities, loans, and subscriptions are assigned to the latest paycheck before each bill is due.</p></article><article><div className="feature-icon"><Landmark /></div><h3>Automatic Plaid variance</h3><p>Posted transactions are matched to manual entries, recurring bills, and expected paychecks. Anything unmatched is flagged.</p></article><article><div className="feature-icon"><BellRing /></div><h3>Text-message intervention</h3><p>Users receive an immediate or daily SMS when undocumented activity exceeds their chosen threshold.</p></article></div></section>
    <section className="flow-section"><div><p className="eyebrow">How it works</p><h2>Designed for people who forget to open finance apps.</h2></div><ol><li><span>1</span><div><strong>Connect checking through Plaid</strong><p>SafeSpend creates a starting balance and securely stores an encrypted access token.</p></div></li><li><span>2</span><div><strong>Enter bills and payday timing</strong><p>The app calculates reserved money and a true safe-to-spend figure.</p></div></li><li><span>3</span><div><strong>Let webhooks watch for changes</strong><p>New bank activity is matched automatically against the register.</p></div></li><li><span>4</span><div><strong>Receive a text when action is needed</strong><p>A secure link opens directly to the transaction review screen.</p></div></li></ol></section>
    <section className="security-section"><div><ShieldCheck size={42} /><div><p className="eyebrow">Built responsibly</p><h2>Financial data needs more than a pretty interface.</h2><p>Plaid tokens are encrypted server-side with AES-256-GCM. Supabase Row Level Security keeps every customer’s register isolated. SMS consent is explicit and never preselected.</p></div></div><div className="security-list"><span><Banknote size={18} /> No bank credentials stored</span><span><ReceiptText size={18} /> Auditable notification log</span><span><ShieldCheck size={18} /> Signed webhook verification</span></div></section>
    <section className="cta-section"><h2>Test the behavior before paying for live bank traffic.</h2><p>The included demo has recurring bills, a running register, a simulated bank variance, and the complete review flow.</p><Link className="button primary large" href="/demo">Launch SafeSpend demo <ArrowRight size={18} /></Link></section>
    <footer><div className="brand-row"><div className="brand-mark small">S</div><strong>SafeSpend Register</strong></div><span>Prototype for product validation — not financial advice.</span></footer>
  </main>;
}
